load('matlab_ex7_com2filtros.mat');
figure;
plot(rf(:,1),rf(:,2));
hold on;
plot(u(:,1),u(:,2),'r');
load('matlab_ex8_semfiltro.mat');
figure;
plot(rf(:,1),rf(:,2));
hold on;
plot(u(:,1),u(:,2),'r');
load('matlab_ex9_wn1_885.mat');
figure;
plot(rf(:,1),rf(:,2));
hold on;
plot(u(:,1),u(:,2),'r');
load('matlab_ex9_wn1_2566.mat');
figure;
plot(rf(:,1),rf(:,2));
hold on;
plot(u(:,1),u(:,2),'r');
load('matlab_ex10_comfiltro.mat');
figure;
plot(rf(:,1),rf(:,2));
hold on;
plot(u(:,1),u(:,2),'r');
load('matlab_ex10_semfiltro.mat');
figure;
plot(rf(:,1),rf(:,2));
hold on;
plot(u(:,1),u(:,2),'r');
load('matlab_ex11a.mat');
figure;
plot(rf(:,1),rf(:,2));
hold on;
plot(u(:,1),u(:,2),'r');
load('matlab_ex11b.mat');
figure;
plot(rf(:,1),rf(:,2));
hold on;
plot(u(:,1),u(:,2),'r');